### ISSUE TITLE
Git Clone in readme.md fails in certain circumstances

### ISSUE THREAD

**Issue by jaapbrasser** [rubrikinc/rbkcli#22]
**Expected Behavior**

I expect to be able to clone the repo, but the default example in readme.md fails because of no SSH key. This can be avoided by using https instead of ssh.

**Current Behavior**

Fails when git clone is executed

**Steps to Reproduce**

```
git clone git@github.com:rubrikinc/rbkcli.git
```

```
git clone https://github.com/rubrikinc/rbkcli
```

**Failure Logs**

<!-- Please include any relevant log snippets or files here.

```
PS C:\Users\jcjbr> git clone git@github.com:rubrikinc/rbkcli.git
Cloning into 'rbkcli'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by Bmanesco** [comment]
Thanks for reporting, the PR has been merged, closing this.
