### ISSUE TITLE
Accept DNS names

### ISSUE THREAD

**Issue by keilma** [rubrikinc/rbkcli#6]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
At the moment only a IP is accepted and a hostname / fqdn does not work:

PS C:\Users\mkeil.SVA> rbkcli cluster me
Rubrik server IP: my.name.tld
Rubrik server IP: a.b.c.d
EnvironmentHandler # No cached API found for this target, importing APIs...

**Describe alternatives you've considered**

**Additional context**
Why is it not possible to use DNS names?

**Comment by Bmanesco** [comment]
Hello Keilma, 

   Thank you very much for the issue raised.

   I will review the request and plan to implement the DNS resolution for targets (Rubrik server IP).

Thank you!

**Comment by Bmanesco** [comment]
Hello Keilma,

  I have added support for fqdn resolution (for target IP) in the following commit:
https://github.com/rubrikinc/rbkcli/commit/d718739aeec92cbf826bb3d712718ef10d25996b

  Please download and install the newer version of the source code available at:
https://github.com/rubrikinc/rbkcli/tree/python27

  Let me know if that works as expected.

Thank you!

**Comment by Bmanesco** [comment]
Changes resolving the FQDN for Rubrik targets are now available on master. Closing this issue. Thank you.
